# Generated by Django 4.2.3 on 2023-07-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_staffs',
        ),
    ]
