# Generated by Django 4.2.3 on 2023-08-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_rooms_alter_message_room_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
