# Generated by Django 4.2.3 on 2023-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_remove_rooms_participants_delete_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ('timestamp',),
            },
        ),
    ]
