# Generated by Django 4.2.3 on 2023-08-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
