# Generated by Django 4.2.3 on 2023-08-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_room_message_globalmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalMessage',
            new_name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
