# Generated by Django 4.2.3 on 2023-08-11 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_chatmessage_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
