# Generated by Django 4.2.3 on 2023-08-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0020_chatmessage_sender_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
