# Generated by Django 4.2.3 on 2023-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0023_follow_news_followering_count_news_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Followering_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Followers_count',
        ),
        migrations.AddField(
            model_name='user',
            name='Followering_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
