# Generated by Django 4.2.3 on 2023-08-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0024_remove_news_followering_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Followering_count',
            new_name='following_user',
        ),
    ]
