# Generated by Django 4.2.3 on 2023-08-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0025_rename_followering_count_user_following_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following_user',
            new_name='Followering_count',
        ),
    ]
