# Generated by Django 4.2.4 on 2023-09-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0035_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
