# Generated by Django 4.2.4 on 2023-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0038_newslike_delete_usernewsrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='total_dislikes',
        ),
        migrations.AlterField(
            model_name='newslike',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
