# Generated by Django 4.2.4 on 2023-09-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0039_remove_news_total_dislikes_alter_newslike_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslike',
            name='liked',
        ),
    ]
