# Generated by Django 4.2.4 on 2023-09-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0040_remove_newslike_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='total_likes',
        ),
    ]
