# Generated by Django 4.2.4 on 2023-09-06 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0041_remove_news_total_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='news',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NewsLike',
        ),
        migrations.AddField(
            model_name='rating',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.news'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'news')},
        ),
    ]
