# Generated by Django 4.2.4 on 2023-09-07 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0043_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
