# Generated by Django 4.2.4 on 2023-09-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0044_user_blocked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_by',
        ),
    ]
